### PR TITLE
Fix copy script/link tag button in lib detail view

### LINKED ISSUE #84: Should have "Copy Script/Link Tag" option in copy button in library page
We only have it in search result now.

### PR DESCRIPTION
**Pull request by francisbrito**
Closes #84

### CODE REVIEW

**Comment by francisbrito** [comment]
Hmmph. Just realized this fix breaks another behavior. Closing it until I get it working again.

**Comment by PeterDaveHello** [comment]
@francisbrito You can add [WIP] in PR title amd let it opened.

**Comment by francisbrito** [comment]
Thanks for the suggestion @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@francisbrito NP

**Comment by francisbrito** [comment]
@PeterDaveHello It works as expected now.

**Comment by PeterDaveHello** [comment]
Thanks @francisbrito ! :+1:

**Pull request merged**
