### PR TITLE
Display total search results

### PR DESCRIPTION
**Pull request by qas612820704**
#176 
screenshot from 2017-05-10 00-28-45

How about this? :)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Looks nice!

**Comment by PeterDaveHello** [comment]
I'll merge this once #161 was merged!

**Comment by PeterDaveHello** [comment]
Hi @qas612820704! I just merged #161, would you like to resolve the conflicts so that we can merge it? Thanks a lot.

PS: Please leave a comment here once you updated it, as there would be no notifications triggered by commit updates, thanks.

**Comment by PeterDaveHello** [comment]
Merged #161 by accident ... lol ... will get it done soon.

**Comment by PeterDaveHello** [comment]
Hi @qas612820704! I just merged #161 (https://github.com/cdnjs/new-website/issues/161), would you like to resolve the conflicts so that we can merge it? Thanks a lot. 
 
PS: Please leave a comment here once you updated it, as there would be no notifications triggered by commit updates, thanks.

**Comment by qas612820704** [comment]
@PeterDaveHello,  fix conflict!

**Comment by PeterDaveHello** [comment]
Thanks a lot for your contribution!

**Pull request merged**
