### PR TITLE
Community dropdown, add subreddit

### PR DESCRIPTION
**Pull request by MattIPv4**
Add the subreddit link, convert community to a dropdown.
Can add the Discord, if created, at a later date.

### CODE REVIEW

**Comment by MattIPv4** [comment]
Probably worth holding off merging this until conversation with @thomasdavis is completed regarding Discord. :)

**Comment by MattIPv4** [comment]
@thomasdavis good to merge?

**Comment by MattIPv4** [comment]
@PeterDaveHello Could you possibly merge as I can't?

**Comment by PeterDaveHello** [comment]
@MattIPv4 I'll take a look soon, thanks.

**Pull request merged**
