### PR TITLE
Localize website

### PR DESCRIPTION
**Pull request by e-jigsaw**
#34 

Added a `language` option. For example,

```
  app.get('/', function(req, res) {
    setCache(res, 2);
    res.send(generatePage({
      page: {
        template: templates.home,
        data: {packages: LIBRARIES}
      },
      language: 'ja'
    }));
  });
```

then

I do not know how to change language option dynamically. If it can change, it works.

Also I will translate the rest of pages, if this is good for you.

Thanks

[Review on Reviewable](https://reviewable.io/reviews/cdnjs/new-website/35)

### CODE REVIEW

**Comment by thomasdavis** [comment]
Great work @e-jigsaw, we should be able to figure out the languag via the sub domain in the request host.

so if `ja.cdnjs.com` {language:'ja'}

**Comment by e-jigsaw** [comment]
@thomasdavis like https://github.com/bmullan91/express-subdomain ?

**Comment by e-jigsaw** [comment]
```js
req.headers.host.split('.')
// => [ 'ja', 'localhost:5000' ]
```

this is it

**Comment by e-jigsaw** [comment]
@thomasdavis I exported all page sentences to yaml. And translated in Japanese.

I think this PR is ok to merge. Is there anything I should do?

Thanks

**Comment by PeterDaveHello** [comment]
hi @e-jigsaw, sorry for the late reply, I wonder if you can rebase with our latest master?
and I'll need @thomasdavis to confirm if we can support this feature now, thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response, sorry.

**Pull request closed without merging**
