### PR TITLE
added jamatto donate buttons as suggested by PeterDaveHello

### PR DESCRIPTION
**Pull request by jimmejardine**
added as suggested by https://twitter.com/PeterDaveHello/status/833054712249274369

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
What do you think about this service @MattIPv4 @drewfreyling @ryankirkman ?

**Comment by MattIPv4** [comment]
@PeterDaveHello I have never personally heard of this service before, do we know who the money goes to?

Why are the buttons for it using custom elements are being placed on the library page instead of in the support us dropdown with all other methods of donating?

**Comment by jimmejardine** [comment]
Hi guys - thanks for considering this addition.  Contributions on this page would accumulate towards the 'cdnjs' business id.  You can claim ownership of this business id by emailing support@jamatto.com, after which you'd have access to the monetization performance dashboard and indicate how you want contributions to be distributed to you.

It was considered that asking for small contributions towards cdnjs would make more sense on the libraries pages as it is those that are visited frequently and the appeal is at a time when the visitor is most likely to be grateful for the awesome service that is cdnjs.  If someone is of the mind to actively seek out your donations page, then let them be funnelled towards the larger contributions at that point.

You can see Jamatto in action e.g. on:
https://www.ebony.com/news/gabrielle-union-explains-support-stepson-pride/#abc6
https://www.limerickleader.ie/news/patricia-feehily-don-t-mind-me/204083/The-life-lessons-learnt-by-not.html#abc2

**Comment by MattIPv4** [comment]
@jimmejardine The support us dropdown is positioned at the top of every single page on the cdnjs site?

**Comment by jimmejardine** [comment]
@MattIPv4 i hear you.  it is more about the size and frequency of the contribution.  if someone is going to be regularly tipping just 20c-50c then it kind of needs to be a zero-friction 'tip on the way our the door.'  If someone wants to contribute $20-$100 then they are probably happy to wait for another page load etc.

**Comment by MattIPv4** [comment]
@jimmejardine Yeah that makes sense, I'm just not very sure about having it so "in your face" on the libraries page, it doesn't really align with the design of the site, nor how cdnjs generally operates. We provide options to donate if users want to but don't shove it in their faces.

My other concern is your rates. Your site really appears to keep this well hidden apart from the create business page where you note the fee in small text in the footer, which is a huge flat rate of 20%.

**Comment by jimmejardine** [comment]
By no means do we mean to hide the rates.  They are there at business creation time and in the T&Cs.  

Owing to the nature of tiny small payments, fixed payment processing fees (e.g. 20c+3% for credit cards or paypal) are quite substantial relative to the actual payment - e.g. for a 20c payment, you'd actually lose money; for a 50c payment, the fee is north of 40%.  Jamatto's 20% finds a compromise between the two.  For some of our clients where consumers are by now topping up their wallets with $5-$10, we have reduced that 20% appropriately.

In terms of the first $1 being free, that is what gets people into the habit of contributing.  If you have regular users, I am confident they will top up (we see evidence of this on dozens of sites).  Also, as our network grows, you receive even the sub-$1 contributions no matter on which site the consumer tops up - the wallet is shared across all sites.

**Comment by jimmejardine** [comment]
All I can suggest is give it a try for a few weeks and see the results.  If they fly, you are golden,  If not, it is a simple reversion.  This is essentially what we have told all our clients, and most have retained and/or grown their use of these small payments.  If you are worried about the cosmetic location, another option might be in the menubar next to the Support us link.

**Comment by MattIPv4** [comment]
Financially, I'll leave the decision to @PeterDaveHello / @ryankirkman 

With regards to the $1 issue, I am still confused by how this works.
Do we get this $1 either way immediately, d does your company cover this until the user tops up?
If not, does it essentially mean the user may think they've donated $1 but they aren't charged and we don't get the money?

**Comment by jimmejardine** [comment]
The latter.  They think they have donated (and in a sense they have committed to that donation in that whenever/wherever they do top up, that donation will flow through to the seller/merchant), seen how easy it is, donate again and again, and ultimately top up (over 70% of people top up once they have extinguished their free $1 over more than 2 transactions...)

**Comment by MattIPv4** [comment]
This seems like a major flaw for a service that is aimed at one time transactions over monthly support. We receive very few contributions financially as it is from my understanding, I doubt many (if any) users would contribute financially multiple times within a short time period, so to lead the user to believe they have donated to us when they aren't charged and we don't get any money seems ridiculous.

To me, it seems that your company should give that $1 to us immediately and take the hit until the user tops up their wallet if you have such confidence in that users will top up their wallets at a later date. If you don't want to take that hit, it screams to me that you don't actually have faith that users will top up their wallets, in which case this makes no sense for us to use at all, as we don't get the donations anyway.

**Comment by jimmejardine** [comment]
You do have a great point.  Once we get that top-up rate past 80% we will very much be considering covering that free amount ourselves (as the rest is broadly covered by our fee).  We are also building out of necessity the tech to make sure that such a mechanism would not be taken advantage of.  At the moment there is no incentive for fraudsters to spoof 'buyer' accounts as the system requires them to participate on both the buying and selling.  Offering free monies very quickly attracts all manner of fraudsters.

But I must reiterate - this is not about once-off contributions.  The entire premise is that by making it really simple and frictionless for someone to transact a small amount, they are happy to do so regularly.  This is born out by what we see across most of our customers.  cdnjs must certainly have massive numbers of repeat visitors (I literally visit it once a week!).

If you don't like it appearing for everyone's first visit, one of my team would be happy to implement a version that appears only after a consumer has visited 2+ or 3+ times...

**Comment by MattIPv4** [comment]
Right okay. My personal opinion is that we don't merge this for now, maybe once we know for sure that we get the donation immediately, up front. I am very skeptical of any service where the "creator" doesn't get the money users believe they are donating.

I'll leave the final decision regarding this to @PeterDaveHello / @ryankirkman however.

**Comment by MattIPv4** [comment]
Closing this - we have the ability for users to donate through GitHub Sponsors, BountySource, Open Collection & Patreon.

**Pull request closed without merging**
