### PR TITLE
Add npm run scripts

### PR DESCRIPTION
**Pull request by rpidanny**
Adds `npm` run commands.

- `npm run start:api`
- `npm run start:web`
- `npm run dev:api`
- `npm run dev:web`

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@rpidanny cool, thanks. Would you like to help remove Makefile in the same PR but another commit? I suppose we shound't maintain them both.

**Comment by rpidanny** [comment]
@PeterDaveHello i've removed `Makefile` and updated `package.json` to reflect the functionalities present in `Makefile`.

**Comment by PeterDaveHello** [comment]
@rpidanny thank you!

**Comment by PeterDaveHello** [comment]
Looks good to me, just a small point here, @rpidanny would you mind me to squash the commits into one(so that I can help edit the commit message on GitHub) or would you like to help us writing more precise commit message with some details? We'd like to follow the conventions in this [post](https://chris.beams.io/posts/git-commit/), FYI. Thanks for your contribution!

**Comment by rpidanny** [comment]
Thanks for the link @PeterDaveHello .

I have updated the commit messages but please feel free to squash the commits if necessary.
Will keep the convention in mind next time :)

**Comment by rpidanny** [comment]
@PeterDaveHello Yes it does. Updated the commit messages.
Thanks for the feedback :+1:

**Comment by PeterDaveHello** [comment]
@rpidanny thank you.

**Pull request merged**
