### PR TITLE
Add `package-lock.json` to .gitignore

### LINKED ISSUE #257: Missing package-lock.json file
While following the *README.md*, a _package-lock.json_ file is created, if the user installs the dependencies through _npm_. Shall we add this file to repository?

### PR DESCRIPTION
**Pull request by MattIPv4**
Resolves #257 by adding the `package-lock.json` file to `.gitignore`.

### CODE REVIEW

**Comment by drewfreyling** [comment]
Why do we want to ignore it?

**Comment by MattIPv4** [comment]
@drewfreyling It isn't something that we track, so having in the gitignore file makes life easier for all involved.

**Comment by Glennmen** [comment]
I don't see why you would want to ignore `package-lock.json`, doesn't having this file improve development because everyone tests/develops using the same package versions.

**Comment by Glennmen** [comment]
There is actually a `package-lock.json` file in the `public/` folder but hasn't been updated: https://github.com/cdnjs/new-website/blob/master/public/packages.min.json

**Comment by MattIPv4** [comment]
@Glennmen That is a minified version of all the packages we host on cdnjs, not related to the npm package versions for the site itself.

**Comment by Glennmen** [comment]
@MattIPv4 My bad 😅

Peter said: `I don't think we really need to add it.`, maybe he didn't think about package version consistency between different local setups.

**Comment by drewfreyling** [comment]
Consistency between dev and ci servers is a major plus for keeping it.

**Comment by MattIPv4** [comment]
@PeterDaveHello What are your thoughts on this?
We (Drew/Glenn/I) are in agreement that we should actually be tracking this file in the repo, not having it untracked (and ignored in this PR).

**Comment by MattIPv4** [comment]
cc #257

**Comment by MattIPv4** [comment]
No progress or response on this. I think down the road we should track this file to ensure consistency between dev envs and deloyments etc.

**Pull request closed without merging**
