### PR TITLE
Preload the resource on copy successfully

### PR DESCRIPTION
**Pull request by int64ago**
Hi, i did a little work to preload the resource after copying, i think it brings a better experience.
Thanks for reviewing this :-)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
I wonder if we really need it, once the link or tag been copied, what they need to do is to paste it on their source code, they don't need to checkout the content or download it, am I right? cc @cdnjs/team-cdnjs @cdnjs/website

**Comment by int64ago** [comment]
But i think the first thing we do normally is to check the link is correct.
And even we paste it in source code, we often test the page locally, so
what do you think then?

**Comment by PeterDaveHello** [comment]
I would like to ask comments from @thomasdavis @terinjokes @ryankirkman @redox and @IonicaBizau

**Comment by IonicaBizau** [comment]
> I wonder if we really need it, once the link or tag been copied, what they need to do is to paste it on their source code, they don't need to checkout the content or download it, am I right?

:+1: I agree! At least, that's what I do.

> But i think the first thing we do normally is to check the link is correct.

@int64ago Is there a visual feedback in case the link is not correct? Or what is `$.get(url, null)` supposed to do?

**Comment by int64ago** [comment]
It's just a experience improvement not function, especially in location
with bad network. Of course, the link almost 100% correct, but what if a
person want to check it? It just let him to get result quickly.

**Comment by IonicaBizau** [comment]
@int64ago That's what I'm trying to understand. How does the user know if the link is accessible or not?
On the other side, if the user has a bad internet connection (s)he would probably do `wget <url>` to download the file, instead of using our cdn. :smile:

**Comment by int64ago** [comment]
Here `bad network` not means `can't access`, i mean it's slow to load. And
most users use cdnjs not for the fast speed in his own computer, he knows
CloudFlare CDN is good for the world, and all-in-one is also the reason.
And users may often directly paste it in browser to check, using wget is
stange.

**Comment by ryankirkman** [comment]
Hey @int64ago, this is pretty interesting!

First, I love the concept of improving user experience.

A couple of things to consider:
- If I am on a bad network, do I want to spend my bandwidth and data allowance pre-loading this script?
  - For users on fast networks, this is less of a concern.
- To confirm, does this actually cache the script in modern browsers? I can imagine some browsers choosing not to cache the result since the `$.get(url, null);` call has no side-effects since nothing is executed.

**Comment by int64ago** [comment]
Hi, @ryankirkman , i think all things you considered is whether the result is cached.
Talking is cheap, i did a small test based on real usage scenes.
 - Search from cdnjs and copy the result
 - Paste it to the source file and open it

Here's my test file, almost does nothing, run as `python -m SimpleHTTPServer` with port 8000
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>test</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <script>
    $(document).ready(function() {
        $('body').html('<h1>test</h1>');
    });
    </script>
</head>

<body>
</body>

</html>
```

No preloading(2s+ for loading):


**Close the window and open another incognito window.**

With preloading(2ms for loading):

**Comment by PeterDaveHello** [comment]
I wonder how much users, in percentage, will need this, if we improve the user experience for about 20% users, but waste the bandwidth of 80% users, that will make no sense.

**Comment by int64ago** [comment]
@PeterDaveHello 
It won't be a waste, for the source a user copied will load sooner or later in the browser of the user.
Of course, if the browser for copying is different from the browser for testing, it's really a waste!
AFASIK, it's too fewer.

**Comment by PeterDaveHello** [comment]
@int64ago hmmmm .... you are right at this point, I just wonder if it's needed. Maybe we should have more disscussion

**Comment by MattIPv4** [comment]
As this is a very old PR, I thought I should add my 2 cents to this...

I think really this change isn't something that should be made. In almost all cases, a developer will be fetching a URL from cdnjs to use in a project that is being worked on in a development context. Therefor, performance on the very first load of this project with the new cdnjs URL isn't key, they will likely expect that the load time may be slower as the new resource needs to be fetched and then cached for future requests.

I also think that for the majority of users, they won't notice or appreciate this change in their load times and it will simply result in the cdnjs.com site silently eating more user bandwidth than necessary without any noticeable benefit for the vast majority.

cc @PeterDaveHello / @ryankirkman what is the plan with this PR going forward, it has become very stale?

**Comment by MattIPv4** [comment]
No progress, closing as the general consensus seems to this isn't needed.

**Pull request closed without merging**
