### PR TITLE
Update library.html template

### LINKED ISSUE #153: Bad font rendering on library template
Hi there! 

## The problem
Currently the number of views,stars and forks of a library is inside the `<i>` html compromising the font-rendering of the number:
image

## Proposed solution
Edit the unordered list inside the library [template](https://github.com/cdnjs/new-website/blob/master/templates/library.html#L11) moving the `<strong>` tag outside the `<i>` tag.

```diff
<ul class="list-inline">
-   <li><i class="fa fa-eye"><strong> {{watch}}</strong></i></li>
+   <li><i class="fa fa-eye"></i><strong> {{watch}}</strong></li>
-   <li><i class="fa fa-star"><strong> {{star}}</strong></i></li>
+   <li><i class="fa fa-star"></i><strong> {{star}}</strong></li>
-   <li><i class="fa fa-code-fork"><strong> {{fork}}</strong></i></li>
+   <li><i class="fa fa-code-fork"></i><strong> {{fork}}</strong></li>
</ul>
```

After that it should be fine 👍 
_example_
image

### PR DESCRIPTION
**Pull request by PaoloFalomo**
fix #153 Bad font rendering

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Thanks for your contribution @PaoloFalomo, the website will be updated with in 15 mins!

cc @pvnr0082t

**Comment by PaoloFalomo** [comment]
Glad to help the open source world 🌐 🎆

**Comment by PeterDaveHello** [comment]
@PaoloFalomo Welcome to join, if you are interested in CDNJS, we have lots of issue there :)

**Comment by PaoloFalomo** [comment]
@PeterDaveHello oh! Great! I'll see where i can help. I'm expert on js,html,css,php

**Comment by PeterDaveHello** [comment]
@PaoloFalomo Awesome, thanks a lot!

**Pull request merged**
