### PR TITLE
start to use SRI on cdnjs.com

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Firefox now has bug that will always give this error in the console:

```
None of the "sha256" hashes in the integrity attribute match the content of the subresource.
```

So will wait for the problem been solved.

### CODE REVIEW

**Comment by ScottHelme** [comment]
Do you have an example of a particular script? I've setup a test site and tried a few, they seem ok.

**Comment by PeterDaveHello** [comment]
@ScottHelme they are all in the PR. See: https://github.com/cdnjs/new-website/pull/139/files

**Comment by PeterDaveHello** [comment]
Related: https://github.com/jekyll/jekyll-assets/issues/270

**Comment by ScottHelme** [comment]
I included a selection here and they seem ok: http://107.170.203.145/

**Comment by PeterDaveHello** [comment]
@ScottHelme would you like to try to clone this repo and run the web server from this PR?

If you want, here are the steps:

```sh
git clone --depth 10 --recursive --shallow-submodules git@github.com:cdnjs/new-website.git
cd new-website
npm install
./webServer.js --local
```

**Comment by PeterDaveHello** [comment]
hmmm ... looks no problem right now, merge this first and keep eyes on it.

**Pull request merged**
