### PR TITLE
Algolia-powered realtime search

### PR DESCRIPTION
**Pull request by redox**
Hey guys/@PeterDaveHello,

Following up on https://github.com/cdnjs/cdnjs/pull/4078#issuecomment-65888765, I've added an Algolia-powered searchbar to the cdnjs.com website. Let me know if you like it!

realtime search

PS: I'll then share with you the Algolia.com credentials + add some [DSN](http://www.algolia.com/dsn) locations.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hello @redox , is it possible that give us an account to view the analytics on algolia? Thank you :smile:

**Comment by thomasdavis** [comment]
@PeterDaveHello I have the account creds, checking now to see if I can share

**Comment by PeterDaveHello** [comment]
@thomasdavis Oh nice!

**Comment by thomasdavis** [comment]
@PeterDaveHello emailed

**Comment by PeterDaveHello** [comment]
@thomasdavis Thanks, let me check it now.

**Comment by redox** [comment]
> Hello @redox , is it possible that give us an account to view the analytics on algolia? Thank you

I've just added more days of Analytics retention to your plan (was 1 day only), analytics will look better in a few days because based on more queries 👍

**Comment by thomasdavis** [comment]
@redox gods work!

**Comment by PeterDaveHello** [comment]
@redox Thanks 😄

**Pull request merged**
