### PR TITLE
[Website] Improved Library version & CDN provider selector UI

### PR DESCRIPTION
**Pull request by krishnanandreddy**
Spacing between version-selector and cdn-provider-selector for improved UX

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Please provide the screenshot before and after the change, thanks :)

**Comment by krishnanandreddy** [comment]
Before:
before
After:
after

**Comment by PeterDaveHello** [comment]
@krishnanandreddy Thanks!

**Comment by krishnanandreddy** [comment]
@PeterDaveHello  Add contributing guidelines if possible.

**Comment by PeterDaveHello** [comment]
@krishnanandreddy it's a good idea, thanks for suggestion!

**Pull request merged**
