### PR TITLE
A load of updates

### PR DESCRIPTION
**Pull request by MattIPv4**
- Resolves https://github.com/cdnjs/new-website/issues/152 [SRI support on search] (includes, closes https://github.com/cdnjs/new-website/pull/251)
 - Resolves https://github.com/cdnjs/new-website/issues/92 [Missing robots.txt]
 - Resolves https://github.com/cdnjs/new-website/issues/258 [GitHub banner issues]
 - Resolves https://github.com/cdnjs/new-website/issues/143 [BreadcrumbList implementation] (includes _modified_, closes https://github.com/cdnjs/new-website/pull/178)
 - Resolves https://github.com/cdnjs/new-website/issues/255 [Throng dep vuln] (includes, closes https://github.com/cdnjs/new-website/pull/256)
 - Resolves https://github.com/cdnjs/new-website/issues/18  [Mobile issues]

Additionally:
 - Update usage stats on about
 - Add me (MattIPv4) to about
 - Overhaul home (responsive, some key info added)
 - Fix brand consistency
 - Re-order navigation to prioritise browsing libraries
 - Fix bad footer margin

Happy New Year! Let's get cdnjs off to a great start in 2019 🎉

### CODE REVIEW

**Comment by MattIPv4** [comment]
@PeterDaveHello How would you suggest splitting this all up then? Quite a bit of it is intertwined and would likely cause conflicts being split up

**Comment by PeterDaveHello** [comment]
@MattIPv4 One topic, one PR. Conflucts are possible, so there mey be rebasing and conflicts resolving before getting merged.

**Comment by MattIPv4** [comment]
@PeterDaveHello Is there a reason for splitting it up into different PRs though? The commits are split up per change so everything is pretty easily traceable.

Splitting everything up just makes a load of extra work and issues that frankly I don't want to be dealing with.

**Comment by PeterDaveHello** [comment]
@MattIPv4 It's hard to review, and revice.

I guess the reason of extra works is trying to do many things one time, which is not needed.

**Comment by MattIPv4** [comment]
@PeterDaveHello The reason I've packed everything in at once is because some of these changes have been sitting in stale PRs or issues for a long time and I'd rather have them all in one PR so they can just be actually dealt with.

**Comment by PeterDaveHello** [comment]
When I need to review a pull request, I need to review the diff of codes, the outcomes, I don't think it's a good idea to cherrypick every commit in it, instead, per issue per pull request, which means per branch to review, that I think it's a good idea.

**Comment by PeterDaveHello** [comment]
Isn't about stale or not, you can still pick or revise staling PR separately.

**Comment by MattIPv4** [comment]
I really don't have the time or energy to go through all the changes I've made to better cdnjs here again and split them up and then resolve all the conflicts that I've already resolve once here.

If you or someone else want to, feel free, or this PR can just chill like all the others here with no progress.

**Comment by PeterDaveHello** [comment]
@MattIPv4 I'd do it when I have time, but the same here, a proper peer review process won't cost less time or energy than doing the changes, so mixing them up increases the worklod of reviewing, with all due respect.

**Comment by PeterDaveHello** [comment]
@MattIPv4 btw, the review process itself, do you have suggestion about not cherrypick every single commit of them for this PR but can certainly be sure each one works well? I don't know yet. These changes seem not testable to me as a reviewer :(

**Comment by MattIPv4** [comment]
@PeterDaveHello If I was reviewing this, I would spool up the local web server with the changes present and then work through the list I provided at the top of what should be changed and fixed and verify that it's all okay. At the same time just check for anything that is obviously broken due to these changes.

**Comment by PeterDaveHello** [comment]
@MattIPv4 thanks, but this method can't deal with the interaction between different changes, and it's also not strict enough. 

I think #261 is something good to follow, same topic, different steps/commits.

**Comment by MattIPv4** [comment]
- Resolves https://github.com/cdnjs/new-website/issues/152 [SRI support on search] (includes, closes https://github.com/cdnjs/new-website/pull/251)
 - Resolves https://github.com/cdnjs/new-website/issues/92 [Missing robots.txt]
 - **RESPONSIVENESS** Resolves https://github.com/cdnjs/new-website/issues/258 [GitHub banner issues]
 - **RESPONSIVENESS** Resolves https://github.com/cdnjs/new-website/issues/143 [BreadcrumbList implementation] (includes _modified_, closes https://github.com/cdnjs/new-website/pull/178)
 - Resolves https://github.com/cdnjs/new-website/issues/255 [Throng dep vuln] (includes, closes https://github.com/cdnjs/new-website/pull/256)
 - **RESPONSIVENESS** Resolves https://github.com/cdnjs/new-website/issues/18  [Mobile issues]

Additionally:
 - **INFO** Update usage stats on about
 - **INFO** Add me (MattIPv4) to about
 - **INFO/RESPONSIVENESS** Overhaul home (responsive, some key info added)
 - Fix brand consistency
 - **RESPONSIVENESS** Re-order navigation to prioritise browsing libraries
 - **RESPONSIVENESS** Fix bad footer margin

Happy New Year! Let's get cdnjs off to a great start in 2019 🎉

**Comment by Glennmen** [comment]
@MattIPv4 What is the use of this PR... You should never combine different features/improvements into a single PR.

Anyways my code shouldn't be in here, there already is a PR for it and @PeterDaveHello will review it once he has the time.

**Comment by PeterDaveHello** [comment]
@Glennmen sorry for the delay again and thanks for your understanding

**Comment by MattIPv4** [comment]
@Glennmen Hi, the reason behind this PR was fixing quite a few stale issues and PRs to get them sorted for the new year. Previous projects I've worked on were fine with mega PRs, evidently not so here. This PR is in the process of being split up and I have pinged @PeterDaveHello in the relevant PRs.

**Pull request closed without merging**
