### PR TITLE
[Website] restructure navbar

### PR DESCRIPTION
**Pull request by MattIPv4**
remove the broken gource links as the navbar is getting crowded and these are broken anyway

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@MattIPv4 I think @ryankirkman says he'd try to get our Google account back so those links won't be dead, but I'm not sure.

**Comment by thomasdavis** [comment]
Let's just comment it out for now then

**Comment by PeterDaveHello** [comment]
@thomasdavis we have git, so we can just remove it, there is no reason to comment out with git.

**Comment by MattIPv4** [comment]
@thomasdavis @PeterDaveHello Sounds good, I’lol make those changes in a bit. I’ll also chase the old pull request that was working on making the nav more mobile compatible.

**Comment by MattIPv4** [comment]
@thomasdavis How does this look now?

__What did you think of the other idea I sent you in my email?__

**Comment by PeterDaveHello** [comment]
@MattIPv4 not sure what's in the email but I believe everything can be discussed in public ;)

**Comment by MattIPv4** [comment]
@PeterDaveHello Fair enough, was a proposition to create some merch for cdnjs. Any profits can go towards funding cdnjs and it allows the community to rep the service and support us at the same time :)

**Pull request merged**
