### PR TITLE
[Website] Add Google's Sitelinks Search Box

### PR DESCRIPTION
**Pull request by sufuf3**
As #202 said

Maybe this function does not take effect immediately, but I'm not sure.
Because I refer to this link https://bloggerspassion.com/google-site-links-how-to-get-google-sitelinks-for-your-website/.

Thanks.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Do we need to add this to every page or just homepage? Any more strong though or reference? It's a little bit strange to send a PR that you're not sure about its effect though I know some changes need more time to reflect its effects.

**Comment by sufuf3** [comment]
Sorry that I was a little bit confuse with https://wpdeveloper.ie/google-sitelinks-search-box-update/

I also refered these reference:
1. https://moz.com/blog/sitelinks-search-box
2. https://www.ranktank.org/structured-data-sitelinks-search-box-builder/
3. http://jacwang.blogspot.tw/2017/01/google-search-sitelinkjson-ld.html

As Google page said `Add this markup only to the homepage, not to any other pages.`
So, I updated this PR.
Sorry about that.

**Comment by PeterDaveHello** [comment]
I think your reference should be this one: https://developers.google.com/search/docs/data-types/sitelinks-searchbox

**Comment by sufuf3** [comment]
Fix
Please help me review this PR, thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 s/Fix/Fixed./

**Comment by sufuf3** [comment]
I modified that comment, thanks.

**Comment by PeterDaveHello** [comment]
Okay, let's give it a try 👍

**Pull request merged**
