### PR TITLE
feat: download packages.min.json from Google storage

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by MattIPv4** [comment]
This should only be used in production, right? Do we still have the "dev" version of the packages.min.json file in the repo?

If so, we should update readme to have development running info & production running info separately.

**Comment by xtuc** [comment]
I wasn't sure if you use `node ./webServer` or `node ./apiServer` directly or used `APP=api sh runServer.sh`.

I will make sure it's documented properly and not confusing. For dev, we can commit a small version of the current `packages.min.js` and the prod should download it.

**Comment by MattIPv4** [comment]
For dev, I use `npm run dev:web` and `npm run dev:api`.

Does prod use any of the other package scripts related to running, we seem to have a lot?
Eg:
 - `npm run start:web`
 - `npm run start:api`
 - `npm run startWeb`
 - `npm run startAPI`

**Comment by xtuc** [comment]
Prod uses what's inside the [Procfile](https://github.com/cdnjs/new-website/blob/master/Procfile#L1): runServer.sh. I can probably clean up a bit the npm script by the way

**Comment by MattIPv4** [comment]
Ah okay, we should update `runServer.sh` to use `npm run start:web` & `npm run start:api` instead of the raw node commands.

It looks like we can then remove `npm run startWeb` & `npm run startAPI` from package.json

**Comment by xtuc** [comment]
The current public/packages.min.json is 91Mb. I think that's fine for development

**Pull request merged**
